### ISSUE TITLE
Is the source code available?

### ISSUE THREAD

**Issue by khanhvu161188** [neilyoung/djistreamerlib#2]
Hi @neilyoung 
Is the source code of this library available then we can work on it?
Thanks

**Comment by neilyoung** [comment]
No, it is not OpenSource. What do you want to achieve?

**Comment by khanhvu161188** [comment]
@neilyoung i want to stream to different webRTV server as well as plotting on frames before stream but look like the library seems to lock with your server.

**Comment by neilyoung** [comment]
This is the case.
